---
- hosts: all
  tasks:
    - name: add additional repos
      become: true
      apt_repository: repo={{item}} state=present
      with_items:
        - ppa:graphics-drivers/ppa
    - name: update packages via apt
      become: true
      apt:
        upgrade: dist
        update_cache: yes
        cache_valid_time: 86400 # one day
    - name: Install desktop packages
      become: true
      apt:
        name:
        - nvidia-driver-415
        - nvidia-settings
        - libnvidia-gl-415:i386
        - kodi
        - steam
        state: present
    - name: Remove unneeded packages
      become: true
      apt:
        name:
          - xscreensaver
          - lirc
        state: absent
