---
- hosts: all
  tasks:
    - name: add additional repos
      become: true
      apt_repository: repo={{item}} state=present
      with_items:
        - ppa:graphics-drivers/ppa
    - name: update packages via apt
      become: true
      apt:
        upgrade: dist
        update_cache: yes
        cache_valid_time: 86400 # one day
    - name: Install desktop packages
      become: true
      apt:
        name:
        - nvidia-driver-415
        - nvidia-settings
        - libnvidia-gl-415:i386
        - kodi
        - steam
        state: present
    - name: Remove unneeded packages
      become: true
      apt:
        name:
          - xscreensaver
          - lirc
        state: absent
    - name: Allow resume for user
      become: true
      template:
        src: templates/custom-actions.pkla.j2
        dest: /etc/polkit-1/localauthority/50-local.d/custom-actions.pkla
    - name: Enable suspend/resume via remote
      become: true
      template:
        src: templates/mcewakeup.rules.j2
        dest: /etc/udev/rules.d/90-mcewakeup.rules
